import React from 'react'

const Lastsection = () => {
    return (
        <div className="flex flex-wrap md:flex-nowrap items-center justify-center min-h-screen bg-[rgb(245,248,253)] p-5">
          {/* Image container */}
          <div className="md:flex-1   ">
            <img
              className="rounded-lg shadow-lg max-w-[800px] h-96  w-[764px]"
src={require("./images/last.png")}              alt="Descriptive Alt Text"
            />
          </div>
          {/* Text container */}
          <div className="md:flex-1 p-6">
            <h1 className="text-3xl font-bold text-gray-800 mb-4">
            What is a Deepfake?
            </h1>
            <p className="text-lg text-gray-600">
            Deepfakes are generated by using machine learning algorithms to manipulate or replace elements like faces or voices in original videos or images. We developed our deepfake detection technology to identify these alterations and distinguish between manipulated and authentic content.

DeepBrain AI is committed to advancing artificial intelligence ethically and transparently. We strive to innovate AI applications that are honest, fair, and maintain the highest integrity standards, ensuring AI technology enhances human lives rather than disrupting them.
            </p>
          </div>
        </div>
      );
}

export default Lastsection
